---
title: "Chapitre 2"
description: |
  Dans cette section vous trouverez l'essentiel du chapitre 2
output: distill::distill_article
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```
- Le support 1 introduction aux méthodes comparatives est disponible en format PDF.
Veillez le télécharger  ici

<div class="contributor_org">

`r xfun::embed_file(here::here("files", "introduction aux méthodes comparatives.pdf"), text = "Télécharger le fichier pdf ici")`
</div>

- Le support 2 les autres méthodes comparatives est disponible en format PDF.
Veillez le télécharger  ici

<div class="contributor_org">

`r xfun::embed_file(here::here("files", "les autres méthodes comparatives.pdf"), text = "Télécharger le fichier pdf ici")`
</div>

- Le support 3 PER est disponible en format PDF.
Veillez le télécharger  ici

<div class="contributor_org">

`r xfun::embed_file(here::here("files", "PER.pdf"), text = "Télécharger le fichier pdf ici")`
</div>

- Le support 4 exercice PER est disponible en format PDF.
Veillez le télécharger  ici

<div class="contributor_org">

`r xfun::embed_file(here::here("files", "exercisePER.pdf"), text = "Télécharger le fichier pdf ici")`
</div>

- Le support 5 la méthode de Fisher est disponible en format PDF.
Veillez le télécharger  ici

<div class="contributor_org">

`r xfun::embed_file(here::here("files", "la méthode de fisher.pdf"), text = "Télécharger le fichier pdf ici")`
</div>

- Le support 6 exemple la méthode de Fisher est disponible en format PDF.
Veillez le télécharger  ici

<div class="contributor_org">

`r xfun::embed_file(here::here("files", "exemple méthode de fisher.pdf"), text = "Télécharger le fichier pdf ici")`
</div>

